theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: Thesis diary
include:
  - abstract.md
  - 07062019.md
  - 14062019.md
  - calendar.md